name: Publish to WinGet

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # - windows-2025
          # - windows-11-arm
          # - ubuntu-24.04
          # - ubuntu-24.04-arm
          - ubuntu-slim
          # - macos-26
          # - macos-15-intel
    steps:
      - uses: UnownPlain/winget-releaser@pwsh-file-test
        id: test
        with:
          identifier: zizmor.zizmor
          token: ${{ secrets.WINGET_TOKEN }}
          installers-regex: '^.+\.zip$'
        env:
          KOMAC_GITHUB_OWNER: unpn-org
      - run: echo ${{ steps.test.outputs.pr-url }}
        shell: bash
